### ISSUE TITLE
Implement fallback configs

### ISSUE THREAD

**Issue by boformer** [zml2008/configurate#12]
The original HOCON ``Config`` class has a ``setFallback(Config config)`` method.
(This example is using the old Sponge ``ConfigFile`` class)
```java
URL fallbackUrl = getClass().getClassLoader().getResource("FallbackInsideJar.conf");
ConfigFile config = ConfigFile.parseFile(configFile).withFallback(fallbackUrl);
config.save(true);
```
This is a really important feature. First of all, it simplifies the code that is needed to initialize the config.
It also simplifies config updates (new plugin version adds some new config nodes).

I found no way to replicate this behaviour with your ``HoconConfigurationLoader``.

It is possible to initialize a config with a ressource from a jar (looks really ugly), but that doesn't fully replace the fallback method:

```java
if (!configFile.exists()) 
{
    configFile.createNewFile();
    
    ConfigurationLoader initialConfigLoader = HoconConfigurationLoader.builder()
    .setSource(Resources.asCharSource(fallbackUrl, UTF8_CHARSET))
    .setSink(Files.asCharSink(configFile, UTF8_CHARSET)).build();

    initialConfigLoader.save(initialConfigLoader.load());
}
```

**Comment by zml2008** [comment]
Something like this could be useful. I'm thinking about implementing this as a ConfigurationNode#mergeValues(ConfigurationNode other) method, which sets everything currently unset on the current node to its values in the node other.

Does that work for you?

**Comment by boformer** [comment]
Yes, I think that works. Also think about an easy way to load a config from a jar resource.

**Comment by zml2008** [comment]
The current way to do that is in a Builder setURL to someClass.getResource("my-resource.conf");

**Comment by boformer** [comment]
Oh, my bad, that's a good way.
So the only thing that is missing is the ``mergeValues`` method
