### ISSUE TITLE
Duplicate comments when saving to file

### ISSUE THREAD

**Issue by bloodmc** [zml2008/configurate#14]
I appear to be getting duplicate comments when attempting to save my configs.

Config with problem can be found here

http://pastie.org/private/zmglkyohfbx8k2p2emx4xa

When testing getComment on each node I get no duplicates so the issue seems to be only when writing the node objects to file.

**Comment by zml2008** [comment]
Fixed in 5bf52925daf488722a3ae3145226902eae37c102
