### ISSUE TITLE
[Feature] Add ability to add a header to config file

### ISSUE THREAD

**Issue by bloodmc** [zml2008/configurate#15]
It would be very useful if you could set a header (comment) at top of config file. Maybe something such as configManager.setHeader(header)

**Comment by zml2008** [comment]
I can probably implement this as setting the comment on the root node.

**Comment by bloodmc** [comment]
Sounds good.

**Comment by zml2008** [comment]
Well, looking at this more the issue becomes that it can become impossible to distinguish the comment for the first node from the header. Might require a blank line between the two?

**Comment by boformer** [comment]
Blank Line makes sense

**Comment by zml2008** [comment]
Partially implemented as of 17a38512ef2bb6151606097009bb4a8a025034d8 -- headers set using setComment are saved to the configuration file, but headers are not yet loaded back. The ambiguities that arise when the first commented lines may be either the header or the comments on the first node are kinda hard to get around.

**Comment by boformer** [comment]
Suggestion: When no header comment was set, still put a empty line at the beginning. The first empty line then always marks the end of the header comment.

When no empty line follows a comment at the beginning of the file, it belongs to the next node.

**Comment by zml2008** [comment]
we don't control input so we can't guarantee that this blank line will be maintained, and a blank line at the beginning of the file looks ugly so doesn't really give us anything. basically we have to be able to rewind the input stream if we misread the header.
