### ISSUE TITLE
Comments with multiple lines

### ISSUE THREAD

**Issue by boformer** [zml2008/configurate#16]
It should be possible to add multiline comments for detailed descriptions. To add this feature, the ``CommentedCOnfigurationNode`` should be modified:
```
public List<String> getComments();
public CommentedConfigurationNode setComments(String ... comment);
```
Example config:
```
# ConfigurateTest Config File
# ---------------------------
#
# This is a summary of this file.
# The summary has multiple lines. And empty lines:
#
# (c) boformer 2015 
{
	# The Version of this config. This is a one-line comment.
	version = 7
	
	# Some config values are complex and need a multiline description.
	# Possible Values: RED, GREEN, BLUE, YELLOW, BLACK
	color = RED
	
	# Time until server explodes
	timeout = 30
	
	# Name of the AI
	ai-name = GLaDOS
}
```

**Comment by zml2008** [comment]
Use \n

**Comment by boformer** [comment]
That doesn't solve the issue!

It has to detect the multiline configs when loading a commented config

Also, using ``\n`` doesn't work correctly:
Input: ``config.getNode("test").setValue(1).setComment("Hello\nWorld");``
Output:
```
# Hello
World
test=1
```
You can guess what happens when you try to load this config:
``Exception in thread "main" com.typesafe.config.ConfigException$Parse: Reader: 3: Key 'World' may not be followed by token: 'test' (if you intended 'test' to be part of the value for 'World', try enclosing the value in double quotes)``

When I use this hacky workaround, it produces a better result:
``config.getNode("test").setValue(1).setComment("Hello\n# World");``

```
# Hello
# World
test=1
```

When You load and save it again, this is the result (because it doesn't handle multiline comments):
```
# Hello
 World
test=1
```
Guess what happens when you try to parse it now ;)
