### ISSUE TITLE
Improve formatting (HOCON)

### ISSUE THREAD

**Issue by boformer** [zml2008/configurate#17]
This input file:
```
# The Version of this config. This is a one-line comment.
version = 7

# The color of tomato
color = RED

# Time until server explodes
timeout = 30

# Name of the AI
ai-name = GLaDOS
```

generates this output:
```
# Name of the AI

ai-name=GLaDOS
# The color of tomato

color=RED
# Time until server explodes

timeout=30
# The Version of this config. This is a one-line comment.

version=7
```

First of all the order of the config nodes changes. I think that is not a good behaviour.
Also, the new lines separate the comments from the config nodes.

I would also prefer "``x = y``" instead of "``x=y``" for the separators

**Comment by boformer** [comment]
Related to https://github.com/zml2008/configurate/issues/18

**Comment by zml2008** [comment]
can't add spaces around = without modifications to the original library.

there shouldn't be blank lines after a comment -- that doesn't parse correctly afaik. I'll look at that.

**Comment by ST-DDT** [comment]
IMO it not needed to have spaces around the `=`. 
This is default properties behaviour, so every developer or server admin is used to it.
Although having it should not cause any issues with the config.
But i don't care whether it will be lost on restart, if there is a way to provide real texts with leading whitespace. And retrieve it from config like that.

**Comment by zml2008** [comment]
There is an issue regarding this opened on the HOCON repo -- typesafehub/config#236. Comment there so the maintainers for HOCON know there is interest in improving this.
