### ISSUE TITLE
Control the order of config nodes

### ISSUE THREAD

**Issue by boformer** [zml2008/configurate#18]
There should be a way to set the insertion point of a config node.

Right now the nodes are sorted by alphabetical order.

**Comment by zml2008** [comment]
concurrent map does not maintain order. got a good implementation that does?

**Comment by zml2008** [comment]
also remember that a lot of config language specs explicitly state that mapping entries are unordered

**Comment by ryantheleach** [comment]
Maintained order shouldn't be relied upon, but would be a useful feature to have in order to have the config readable in a nice order.

**Comment by bloodmc** [comment]
@zml2008 how about switching from a ConcurrentHashMap to ConcurrentSkipListMap ? http://docs.oracle.com/javase/6/docs/api/java/util/concurrent/ConcurrentSkipListMap.html

This would preserve ordering yet sacrifice some performance with insertions but I do not see that as a problem since most of our operations will be read only.

**Comment by zml2008** [comment]
I'll mess with that. People will still whine about insertion order but I think SkipListMap is a good tradeoff.

**Comment by zml2008** [comment]
Fixed in 9263008cfc5cb9229019b5c362c9fdabf0f8bbb8

**Comment by boformer** [comment]
Is it now possible to load a config from a resource and save it without destroying the order?

**Comment by zml2008** [comment]
yeah, just pass the appropriate comparator in ConfigurationOptions to the loader's load(ConfigOptions) method.

**Comment by ryantheleach** [comment]
What would be the appropriate comparator for "keep things in the order they were already in"? Wouldn't this just allow you to apply a custom sort, so that you could sort things, as opposed to avoiding sorting at all?

**Comment by boformer** [comment]
@ryantheleach I thought about that problem as well
