### ISSUE TITLE
Advanced config formatting options (HOCON)

### ISSUE THREAD

**Issue by boformer** [zml2008/configurate#19]
There should be a way to control the output format of config files.

There are 2 types of "containers": Lists ``[1,2,3]`` and Maps ``{a=1,b=2}``.
These containers should have an option to toggle between **single-line** output and **multi-line output**.

Right now this input 
```
formattedMessage = [
	{text: "Please ", color: gold}, 
	{text: "/confirm", color: red, clickEvent: {action:run_command,value:"/confirm"}}, 
	{text: " or", color: gold}, 
	{text: "/deny", color: red, clickEvent: {action: run_command, value: "/deny"}}, 
	{text: " this action.", color: gold}
]
```
is formatted like this when saved to a file:
```
formattedMessage=[
    {
        color=gold
        text="Please "
    },
    {
        clickEvent {
            action="run_command"
            value="/confirm"
        }
        color=red
        text="/confirm"
    },
    {
        color=gold
        text=" or"
    },
    {
        clickEvent {
            action="run_command"
            value="/deny"
        }
        color=red
        text="/deny"
    },
    {
        color=gold
        text=" this action."
    }
]
```

**Comment by zml2008** [comment]
This is a limitation of the underlying library. Go open an issue at [typesafehub/config](https://github.com/typesafehub/config) or write your own ConfigurationLoader with a better hocon-compatible library (and PR it :p) if you want more flexible rendering options. Until then, you're stuck with what's exposed in ConfigRenderOptions.
