### ISSUE TITLE
Automatically create file when saving

### ISSUE THREAD

**Issue by boformer** [zml2008/configurate#21]
Right now it is necessary to manually create the output file when saving a HOCON config:
```
ConfigurationLoader configLoader = HoconConfigurationLoader.builder().setFile(outputFile).build();
if (!outputFile.exists()) outputFile.createNewFile();
configLoader.save(node);
```

The creation of the file should be a part of the ``save`` method.

**Comment by zml2008** [comment]
the file doesn't have to be created. The parent directory has to exist. Also remember that the configuration loaders only see Readers and Writers, not files (you can pass a custom CharSink to the loader that creates the file + parent directories if you really want to make this automatic I guess).
