### ISSUE TITLE
Option to set value to default if absent

### ISSUE THREAD

**Issue by matthewprenger** [zml2008/configurate#22]
Currently if a value is `null` and a default is provided, the default will just be returned be returned. Having an option to also set the value to the default would be nice. This would allow the first save to save all the defaults to disk.

**Comment by boformer** [comment]
I don't know if this is necessary.
There is the ``mergeValuesFrom(ConfigurationNode other)`` method in ``ConfigurationNode`` to load defaults, e.g. from an internal ``defaults.conf`` ressource.

You could also do something like:
```java
String myConfigValue = node.isVirtual() ? node.setValue(theDefaultValue) : node.getString();
```

**Comment by zml2008** [comment]
Yeah, what @boformer said
