### ISSUE TITLE
Saving a YAML configuration re-arranges all keys

### ISSUE THREAD

**Issue by Zidane** [zml2008/configurate#25]
https://github.com/AlmuraDev/Guide/wiki/Template

When simply doing  a save

http://pastie.org/9986041

This shouldn't be that way whatsoever.

**Comment by Zidane** [comment]
Okay, I forgot to set the DumperOptions.

With that said, its still re-arranging my keys.

http://pastie.org/9986056

**Comment by zml2008** [comment]
Ok, fixed the map type. Keys are now sorted by a Comparator provided to the ConfigurationOptions used to create the configuration or natural ordering.

**Comment by boformer** [comment]
Well, that doesn't solve the issue. There is no comparator that keeps the input order.

**Comment by zml2008** [comment]
Looks like there's a concurrent linked hash map: https://code.google.com/p/concurrentlinkedhashmap

Will look into this
