### ISSUE TITLE
TypeSerializer for java.util.Set?

### ISSUE THREAD

**Issue by thomas15v** [zml2008/configurate#35]
I don't know in how far that would be possible. A Set kinda looks the same as a List in a config file :worried:.

**Comment by boformer** [comment]
``new HashSet(myList)``? A list is used because the items in the config are ordered.

**Comment by thomas15v** [comment]
Ehm I don't see how that would help. I have a class with this: ```private Set<UUID> trustedPlayers```. 
I wanted to make sure that their is type wise, no change to get the same player trusted.

**Comment by ryantheleach** [comment]
The problem is that set's have different rules regarding multiples and order then lists.

The only way I see you getting it back from a list to a set without changing the syntax, is to convert it yourself, configurate has no way of knowing what format you need it in unless you tell it the type.

**Comment by zml2008** [comment]
It's better to be specific and correct than to be unspecific and have lots of undefined behavior imo.

Do most of the formats we're using support Sets? I know yaml does with an explicit !!set tag -- but I don't think any other format does. So I'm not sure of the benefit we get to faking support for a collection type most configuration backends don't support

**Comment by zml2008** [comment]
Yeah, I'm not going to add special casing for Strings. Part of my near-term todo list is to add proper by-type value filtering in though which will help make this issue more explicit.
