### ISSUE TITLE
When unpacking a collection for serialization, also unpack the TypeSerializer.

### ISSUE THREAD

**Issue by me4502** [zml2008/configurate#54]
Currently the only way to pass a list to a setValue with a type serializer is to make the type serializer contain `Set<Type>`.

This however throws an exception, such as the following,
ninja.leaping.configurate.objectmapping.ObjectMappingException: No serializer available for type `java.util.Set<com.sk89q.craftbook.sponge.util.BlockFilter>`

Note: There is a serializer for `com.sk89q.craftbook.sponge.util.BlockFilter` available.

As the contract of setValue and getValue implies that Lists are unpacked and appropriately serializable, unpacking for the TypeSerializer needs to be handled inside Configurate as well.

**Comment by ryantheleach** [comment]
Are you sure it's not a Set vs List problem?

**Comment by me4502** [comment]
Yeah I'm sure, I just used those as examples.

**Comment by me4502** [comment]
@zml2008 Any updates on this?

**Comment by zml2008** [comment]
This is because there's no Set TypeSerializer.

**Comment by me4502** [comment]
@zml2008 How would I create a TypeSerializer for Set? Is there a way I can recursively call another type serializer to serialize the contained type?
