### ISSUE TITLE
Correctly handle raw-typed collections

### ISSUE THREAD

**Issue by zml2008** [zml2008/configurate#58]
Brought up by @windy1, it's important to have more sensible handling of raw typetokens -- just assume <Object(, Object)*> in the TypeSerializers.

While this will mean that some objects can't get any deserializing, it will also allow rawer data structures to be used.

**Comment by randombyte-developer** [comment]
@zml2008 Does the 'fix' to this issue prevent a type like this: `List<List<String>>`? I am having problems(`"Raw types are not supported for collections"`) while serializing this.
