### ISSUE TITLE
Configurate Fails to Save to Config, and Creates .tmp Files 

### ISSUE THREAD

**Issue by hsyyid** [zml2008/configurate#59]
**This issue was reported by several users of my Kits plugin.**

[Original Issue](https://github.com/hsyyid/Kits/issues/6)
[Console Log](http://pastebin.com/twEuWMPz)

Basically, when Configurate fails to save something to the config (it says there is an AccessDeniedException) it creates LOTS of `.tmp` files, resulting in server TPS to drop, sever RAM usage to go up, and many more issues.

**Comment by ryantheleach** [comment]
I'm not getting the many tmp files, But I can't work out the correct way to create a new config.

I'm getting an initial path from: 

  @Inject
    @ConfigDir(sharedRoot = false)
    Path configDir;


Then, when a command is called.
CommentedConfigurationNode x = MakeNodeFromObject(obj);
HoconConfigurationLoader.builder().setPath(configDir.resolve("dump.conf")).build().save(x);

results in an IO exception when running in a SpongeForge Dev environment on windows 10, using IntelliJ 2016.1

java.nio.file.NoSuchFileException: config\betterhelp\dump.conf7811837891526123131.tmp

**Comment by zml2008** [comment]
This seems to be a windows-specific issue -- I haven't had a chance to figure out how to set up a development environment on windows to resolve this. Until then, just run on linux or OS X. Maybe even windows 10's linux emulation might work?

**Comment by ryantheleach** [comment]
I'll attempt to debug it further this week then.

**Comment by ryantheleach** [comment]
So assuming that configurate is supposed to make the directories automatically if the path provided does not yet exist, the easy fix for this is to add a 
```
Files.createDirectories(path.getParent());
```

on line https://github.com/zml2008/configurate/blob/bbb93c8a833859071ad8e19032ec798c54b5f0b1/configurate-core/src/main/java/ninja/leaping/configurate/loader/AtomicFiles.java#L40

If not, it may be a user error where sponge / plugins / applications using configurate should create the folder ahead of time.
