### ISSUE TITLE
Multiline Headers lose lines after multiple saves

### ISSUE THREAD

**Issue by Grinch** [zml2008/configurate#64]
Setting a header that has multiple lines starts to lose parts of the header after multiple saving. A good example is simply running https://github.com/SpongePowered/SpongeVanilla (fresh setup) and watch the global.conf file.

**Comment by zml2008** [comment]
So I think I have a fix for this -- could you test https://minions.aoeu.xyz/zml/sv-configfix.jar on windows and see if it works?
