### ISSUE TITLE
Incorrect file permissions

### ISSUE THREAD

**Issue by Nentify** [zml2008/configurate#67]
http://pastebin.com/DTdZTAkP

```
luke@play:~/sponge-vanilla$ umask
0002
```

It seems like Sponge is creating files with 600 permissions (folders seem to be the correct permissions). The files should be 664 (-rw-rw-r--). I've linked a paste showing permissions from vanilla Forge, SpongeForge and SpongeVanilla showing the discrepancies. I'm assuming it's either an issue with Sponge, the config software or my setup. My setup works with everything else though and is pretty fresh out of the box, so I'm not sure why only Sponge would be acting up here.

Thanks for your help!

Copied from https://github.com/SpongePowered/SpongeCommon/issues/869

**Comment by zml2008** [comment]
Fixed in 9fff4501316a62d52a0d80b0031be2d7d453a48b
