### ISSUE TITLE
Enum assumes Uppercase

### ISSUE THREAD

**Issue by hsyyid** [zml2008/configurate#77]
https://github.com/zml2008/configurate/blob/0b6b95818a2cf19a6d46d46c09ec7d637a17b7b9/configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializers.java#L126

**Comment by zml2008** [comment]
enum assumes devs follow proper coding standards... but ill change it, probably make it case-insensitive
