### ISSUE TITLE
Parsing double quotations

### ISSUE THREAD

**Issue by lucko** [zml2008/configurate#80]
Someone in my Discord was having issues with config values being read incorrectly. It turns out that the quotes around the options they'd changed were being included in the values.

The "standard" quotes are just a `"`.
https://unicode-table.com/en/0022/

However, for whatever reason, in their config, they had `“ ”`

https://unicode-table.com/en/201C/
https://unicode-table.com/en/201D/

These weren't being parsed correctly when the config was loaded.

Not sure if this is a configurate issue or something with the HOCON lib, but either way, I'd be great if it could be patched.

Thanks. :)

**Comment by ryantheleach** [comment]
Using those unicode quotes, is pretty indicative of using microsoft word as a text editor instead of a word processor. May have been from elsewhere though.

**Comment by zml2008** [comment]
Quotation marks are unfortunately something that is handled by the hocon library. The most we could do would be perhaps the option to filter input -- but the best way to resolve this would probably be to get it changed in hocon.
