### ISSUE TITLE
CommentedConfigurationNode.getValue(type, def)

### ISSUE THREAD

**Issue by Tsugaga** [zml2008/configurate#84]
CommentedConfigurationNode.get(TypeToken.of(MyClass.class), new MyClass(args...));

This works great and my TypeToken is working, however I noticed that when it returns a transformed value, it also still creates the default new MyClass() object.

**Comment by lucko** [comment]
Use the method which accepts `Supplier<T>` as opposed to just `T`. The supplier will only be called if a transformed value can't be obtained.

https://github.com/zml2008/configurate/blob/master/configurate-core/src/main/java/ninja/leaping/configurate/ConfigurationNode.java#L382

e.g.
```java
node.get(TypeToken.of(MyClass.class), () -> new MyClass(args...));
```
